### PR TITLE
add a heat haze animation effect to the forcefield

### PR DESCRIPTION
**Pull request by sweet235**
This is becoming the new standard effect for forcefields:

unvanquished_2024-09-14_175723_000

(this screenshot is now outdated, use the .dpk file below)

But you need to look at it ingame to decide if you like it, as it moves.

### CODE REVIEW

**Comment by illwieckz** [comment]
I'm not sure about the movement and deform because it looks like water too much for me.

**Comment by sweet235** [comment]
With `tcmod scale .5 .5`, this blinks occasionally. Maybe at some point in time, the scroll is reset. And somehow, this does not happen seamlessly. I have yet to understand how this works.

~~I guess we could simply reduce the heathaze image to one of its quarters and set the scale back to 1.~~ (that would not tile)

I will push a 256x256 heat haze image soon.

**Comment by sweet235** [comment]
I think the 256x256 heathaze map scaled to 1 looks very similar to the 512x512 map scaled to 0.5.

TODO: delete one of the images

**Comment by illwieckz** [comment]
> With `tcmod scale .5 .5`, this blinks occasionally. Maybe at some point in time, the scroll is reset. And somehow, this does not happen seamlessly. I have yet to understand how this works.

Maybe a bug:

- https://github.com/DaemonEngine/Daemon/issues/1278

**Review by illwieckz — APPROVED** [review]
LGTM.

**Comment by illwieckz** [comment]
I converted png to lossless webp, kept the 256 one, and squashed.

**Comment by sweet235** [comment]
Here is a loadable package for review:

[map-plat23_1.13.4-for-review.dpk.zip](https://github.com/user-attachments/files/17023407/map-plat23_1.13.4-for-review.dpk.zip) (remove the `.zip`, thanks github)

It depends on `map-plat23_1.13.4.dpk`.

**Pull request merged**
